---
apiVersion: apps/v1
kind: ReplicaSet 
metadata:
  name: jenkins-rs
spec: 
  minReadySeconds: 10
  replicas: 2
  selector:
    matchLabels:
      app: jenkins 
      ver: "1.0"
  template:
    metadata:
      name: jenkins-prd 
      labels:
        app: jenkins 
        env: QA
        ver: "1.0"
    spec:
      containers:
        - image: jenkins/jenkins:lts-jdk11
          name: jenkins-sv
          ports: 
           - containerPort: 8080
             protocol: TCP
          resources: 
            requests: 
              memory: "512Mi"
            limits:
              memory: "1024Mi"

