---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx 
spec: 
  minReadySeconds: 5 
  replicas: 4
  selector: 
    matchLabels:
      app: web 
  template:
    metadata:
      labels:
        name: nginx 
        app:  web
        ver: "1.0"
    spec:
      containers: 
        - name: nginx 
          image: nginx:1.23
          ports:
            - containerPort: 80
              protocol: TCP 
        

      
      
