--- 
apiVersion: v1 
kind: Service 
metadata:
  name: nigix-svc 
spec:
  selector:
    name: nginx 
    ver: "1.0" 
  type: ClusterIP 
  ports:
    - name: webport
      port: 35000 
      targetPort: 80