apiVersion: v1
kind: ReplicationController 
metadata:
  name: nginx
spec:
  minReadySeconds: 3
  replicas: 5
  template:
    metadata:
      name: nginx-dev
      labels:
        app: nginx 
        ver: "1.23"
    spec:
      containers:
        - name: nginx
          image: nginx:1.23
          ports:
            - containerPort: 80
              protocol: TCP          
