--- 
apiVersion: v1
kind: Pod 
metadata: 
  name: init-cont1
spec:
  initContainers:
    - image: alpine:3
      name: init-cont1
      command:
        - sleep
        - "30" 
    - image: alpine:3
      name: init-cont2
      command:
        - sleep 
        - "30"  
  containers:
    - name: nginx
      image: nginx:1.23
      ports:
        - containerPort: 80
          protocol: TCP