---
apiVersion: v1
kind: Pod
metadata:
  name: nigix
spec:
  containers:
    - image: nigix:1.23
      name: myngixsev
      ports:
        - containerPort: 80
          protocol: TCP
    - image: jenkins/jenkins:lts-jdk11
      name: jenkins
      ports:
        - containerPort: 8080
          protocol: TCP
